
# ------------------------------------ #
#      CLIENT DETECTOR CONFIG          #
# ------------------------------------ #

IncludeClientInJoinMessage: false
# The join message will say "Player joined the game using Client" instead of "Player joined the game".

BlockedClients:
  - example
  - example2
# Players will be kicked from the server if they are using a client listed above.

CrashBlockedClients: false
# Instead of kicking them from the server this will display up to 65536(the value of the "DisplayAmount" section below) elder guardian effects crashing their game.

DisplayAmount: 65536
# You normally don't need to change this.

MessagePrefix: "$6$lC$a$lD$b» "
# The "$" is used for colour codes.