name: ClientDetector
version: '1.1.2'
main: me.llamamc.clientdetector.ClientDetector
api-version: '1.13'
author: LlamaMC
description: Allows you to see what client a player is using.
commands:
  client:
    description: Tells you what client a player is using.
    permission: clientdetector.command.client
    aliases:
      - getclient
permissions:
  clientdetector.*:
    description: Gives you every permission related to the Client Detector plugin!
    children:
      - clientdetector.command.*
      - clientdetector.clientblocker.bypass
      - clientdetector.joinmessage.hide
  clientdetector.command.*:
    description: Allows you to use all Client Detector commands.
    children:
      - clientdetector.command.client
  clientdetector.command.client:
    description: Allows you to use the /client command.
  clientdetector.clientblocker.bypass:
    description: Lets you join the server even if you are using a blocked client.
  clientdetector.joinmessage.hide:
    description: Prevents the server from showing your client in the join message.